### ISSUE TITLE
Documentation on tracking a basic event is wrong

### ISSUE THREAD

**Issue by andrewfrankcare** [amplitude/Amplitude-TypeScript#349]
In the README in GitHub for Amplitude SDK for Node.js  you write:

```
// Track a basic event
track('Button Clicked');
```

However, this won't work as you are expecting a user_id or device_id:

```
Amplitude Logger [Error]: Request missing required field
Amplitude Logger [Debug]: {
  "type": "invoke public method",
  "name": "track",
  "args": [
    "Button Clicked"
  ],
  "stacktrace": [
    "at Analytics.trackMessageInference (/Users/aleppard/frank/one/Frank_Slack/queue_consumer/dist/.common/analytics.js:28:36)",
    "at Object.run (/Users/aleppard/frank/one/Frank_Slack/queue_consumer/dist/runSlackMessageInference.js:107:19)",
    "at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "at async handleSQSEvent (/Users/aleppard/frank/one/Frank_Slack/queue_consumer/dist/app.js:51:13)",
    "at async poll (/Users/aleppard/frank/one/Frank_Slack/queue_consumer/dist/poll.js:47:9)"
  ],
  "time": {
    "start": "2023-03-22T22:49:19.052Z",
    "end": "2023-03-22T22:49:29.876Z"
  },
  "states": {
    "before": {
      "config.apiKey": "b8e03107dbf9088cf67165fca4ae0eab",
      "timeline.queue.length": 0
    },
    "after": {
      "config.apiKey": "b8e03107dbf9088cf67165fca4ae0eab",
      "timeline.queue.length": 0
    }
  }
}

```

The documentation elsewhere looks like it might be right:

```
// Track a basic event
track('Button Clicked', undefined, {
  user_id: 'user@amplitude.com',
});
```

**Comment by kevinpagtakhan** [comment]
@andrewfrankcare good catch! Docs here needs an update. For Node SDK, user id or device id or both must be specified.

**Comment by kevinpagtakhan** [comment]
@andrewfrankcare thank you again for pointing this out. I link the PR that resolved this issue. Closing now!

**Comment by ca136** [comment]
Just curious if you have any plans on supporting setting the user_id or device_id in the init method for the node SDK like the the browser SDK? It's a bit of a pain to pass the user_id in every single event.
