### ISSUE TITLE
unhandledRejection: TypeError: globalScope.addEventListener is not a function

### ISSUE THREAD

**Issue by a396901990** [amplitude/Amplitude-TypeScript#487]
I run `next-app` example on yarn dev with this error show up:
`error - unhandledRejection: TypeError: globalScope.addEventListener is not a function`

```
yarn dev
yarn run v1.16.0
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 802 ms (224 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 136 ms (232 modules)
Your Amplitude instance is configured to track Page Views, Sessions, File Downloads, Form Interactions. Visit https://www.docs.developers.amplitude.com/data/sdks/browser-2/#tracking-default-events for more details.
error - unhandledRejection: TypeError: globalScope.addEventListener is not a function
    at Object.<anonymous> (/Users/dean/Amplitude-TypeScript/examples/browser/next-app/node_modules/@amplitude/plugin-page-view-tracking-browser/lib/cjs/page-view-tracking.js:88:41)
    at step (/Users/dean/Amplitude-TypeScript/examples/browser/next-app/node_modules/tslib/tslib.js:193:27)
    at Object.next (/Users/dean/Amplitude-TypeScript/examples/browser/next-app/node_modules/tslib/tslib.js:174:57)
    at /Users/dean/Amplitude-TypeScript/examples/browser/next-app/node_modules/tslib/tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/dean/Amplitude-TypeScript/examples/browser/next-app/node_modules/tslib/tslib.js:163:16)
    at Object.setup (/Users/dean/Amplitude-TypeScript/examples/browser/next-app/node_modules/@amplitude/plugin-page-view-tracking-browser/lib/cjs/page-view-tracking.js:79:59)
    at Timeline.<anonymous> (/Users/dean/Amplitude-TypeScript/examples/browser/next-app/node_modules/@amplitude/analytics-core/lib/cjs/timeline.js:24:107)
    at step (/Users/dean/Amplitude-TypeScript/examples/browser/next-app/node_modules/tslib/tslib.js:193:27)
    at Object.next (/Users/dean/Amplitude-TypeScript/examples/browser/next-app/node_modules/tslib/tslib.js:174:57)
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 122 ms (233 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
```

this is my package.json
```
{
  "name": "next-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@amplitude/analytics-browser": "^2",
    "next": "13.0.6",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  },
  "devDependencies": {
    "@types/node": "18.11.14",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.9",
    "eslint": "8.29.0",
    "eslint-config-next": "13.0.6",
    "typescript": "4.6.3"
  }
}
```

**Comment by moksha-ai** [comment]
I have the same issue, @a396901990 how did you solve it?

**Comment by nabusman** [comment]
I ran into the same error, @a396901990 did you manage to solve it?
