### ISSUE TITLE
Version 2.7.3 introduced some rollup problems

### ISSUE THREAD

**Issue by Boardtale** [amplitude/Amplitude-TypeScript#752]
## Expected Behavior
Ability to vue-tsc project that included "@amplitude/analytics-browser": "2.7.3"

## Current Behavior
Failing when building on pipelines. Locally it works. Local env: Windows, pipelines: Linux

```
> vue-tsc --noEmit -p tsconfig.vitest.json --composite false

/home/vsts/work/1/s/packages/ui/node_modules/rollup/dist/native.js:59
		throw new Error(
		      ^

Error: Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/home/vsts/work/1/s/packages/ui/node_modules/rollup/dist/native.js:59:9)
    at Object.<anonymous> (/home/vsts/work/1/s/packages/ui/node_modules/rollup/dist/native.js:68:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at cjsLoader (node:internal/modules/esm/translators:348:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:297:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
  Require stack:
  - /home/vsts/work/1/s/packages/ui/node_modules/rollup/dist/native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
      at Module._load (node:internal/modules/cjs/loader:986:27)
      at Module.require (node:internal/modules/cjs/loader:1233:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (/home/vsts/work/1/s/packages/ui/node_modules/rollup/dist/native.js:41:10)
      at Object.<anonymous> (/home/vsts/work/1/s/packages/ui/node_modules/rollup/dist/native.js:68:76)
      at Module._compile (node:internal/modules/cjs/loader:1358:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
      at Module.load (node:internal/modules/cjs/loader:1208:32)
      at Module._load (node:internal/modules/cjs/loader:1024:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/home/vsts/work/1/s/packages/ui/node_modules/rollup/dist/native.js'
    ]
  }
}

Node.js v20.13.1
ERROR: "build-only" exited with 1.

```
I get it this might be related to some other updates that 2.7.3 included - upgrading other libraries. But it introduced problems unfortunatly. Would appreciate any help here.
2.7.2 works fine, but wanted to upgrade this lib

## Steps to Reproduce
1. setup linux machine (I am using ADO pipelines: ubuntu-latest
2. Run: vue-tsc --noEmit -p tsconfig.vitest.json --composite false

## Environment
- JS SDK Version: Node 20 + TS on Vue3
- Installation Method: NPM
- Browser and Version: n/a

**Comment by Mercy811** [comment]
Rerun jira ticket creation

**Comment by Mercy811** [comment]
Hi @Boardtale, could you share your CI file? 2.7.3 doesn't include changes affecting rollup steps and doesn't require `@rollup/rollup-linux-x64-gnu`.  Could you also try to rerun your CI with 2.7.2 and the latest version 2.9.1?

**Comment by Mercy811** [comment]
Close this issue as not hearing back.
