### ISSUE TITLE
React Native "Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Property 'btoa' doesn't exist"

### ISSUE THREAD

**Issue by hohoaisan** [amplitude/Amplitude-TypeScript#800]
## Expected Behavior
No error was shown when initialize amplitude with `@amplitude/analytics-react-native` module in React Native

## Current Behavior
The following error log was pushed into console, there is no documentation about polyfilling or disable cookies?
```
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Property 'btoa' doesn't exist
    at apply (native)
    at apply (native)
    at App
    at doResolve (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at apply (native)
    at ErrorOverlay
    at RCTView
    at apply (native)
    at RCTView
    at apply (native)
    at Promise (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at apply (native)
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Property 'btoa' doesn't exist
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Property 'btoa' doesn't exist
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Property 'btoa' doesn't exist
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Property 'btoa' doesn't exist
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Property 'btoa' doesn't exist
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Property 'btoa' doesn't exist
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Property 'btoa' doesn't exist
```

## Steps to Reproduce
1. Install `@amplitude/analytics-react-native` by using `yarn expo install @amplitude/analytics-react-native`
2. Import `import * as amplitude from '@amplitude/analytics-react-native'` in App.tsx
3. Observe the Metro console

## Environment
- @amplitude/analytics-react-native version: ^1.4.9
- Installation Method: yarn
- "react-native": "0.72.6
- "expo": "^49.0.0",

**Comment by hohoaisan** [comment]
After polyfilling btoa, following error log:
```
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Cannot set property 'cookie' of undefined
    at apply (native)
    at apply (native)
    at App
    at doResolve (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:216:25)
    at apply (native)
    at ErrorOverlay
    at RCTView
    at apply (native)
    at RCTView
    at apply (native)
    at Promise (/Users/distiller/react-native/packages/react-native/sdks/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:82:14)
    at apply (native)
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Cannot set property 'cookie' of undefined
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Cannot set property 'cookie' of undefined
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Cannot set property 'cookie' of undefined
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Cannot set property 'cookie' of undefined
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Cannot set property 'cookie' of undefined
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Cannot set property 'cookie' of undefined
 ERROR  Amplitude Logger [Error]: Failed to set cookie for key: AMP_TEST. Error: Cannot set property 'cookie' of undefined
```

**Comment by yuhao900914** [comment]
Thanks for choosing amplitude. 
Did you also install the async storage at the same time?
```
# npm
npm install @amplitude/analytics-react-native
npm install @react-native-async-storage/async-storage

# yarn
yarn add @amplitude/analytics-react-native
yarn add @react-native-async-storage/async-storage
```
[This](https://github.com/amplitude/Amplitude-TypeScript/tree/main/packages/analytics-react-native) is the instruction on how to use amplitude.  There is [more](https://amplitude.com/docs/sdks/analytics/react-native/react-native-sdk) for the developer doc.

**Comment by noma4i** [comment]
https://github.com/amplitude/Amplitude-TypeScript/issues/1228
